### ISSUE TITLE
Task manager screenshots

### ISSUE THREAD

**Issue by jonrp** [fremag/MemoScope.Net#153]
![tm2](https://cloud.githubusercontent.com/assets/19949783/19088629/d5f9ad4c-8a6e-11e6-8868-716b77a2c667.png)
![tm1](https://cloud.githubusercontent.com/assets/19949783/19088630/d5fe46c2-8a6e-11e6-9d0d-02948ce42782.png)

**Comment by fremag** [comment]
Thanks. I will replace the screenshots in french with thses.
