### ISSUE TITLE
Attempting to load an x64 dump into an x86 version gives an unhelpful error dialog

### ISSUE THREAD

**Issue by IanKemp** [fremag/MemoScope.Net#194]
![image](https://cloud.githubusercontent.com/assets/1726434/22280925/924857d0-e2dc-11e6-804f-b67b777475fb.png)

A simple "fix" would be to add some help text to the dialog, directing users to ensure they load x86 dumps using the x86 version of the app and vice versa.

**Comment by fremag** [comment]
Thanks a lot for your feedback. 
There was a message for this kind of issue but it didn't show up.
Should be fixed now.
I will make a new release in github because the last one avaible doesn't include many bugfixes.
