### ISSUE TITLE
Memory dump never finish loading

### ISSUE THREAD

**Issue by artisticcheese** [fremag/MemoScope.Net#197]
Hello,

Just testing this app and can not load memory dump. It's just keep showing "Loading file ..." and never finishes.

**Comment by fremag** [comment]
Hi,

Thanks for your feedback.

I've modified the code so the call to LoadCrashDump file is now in a try/catch block.
If something fails, we should have more information about it.

**Could you try again to load your file with this [version](https://ci.appveyor.com/api/buildjobs/gejr10v31ohx9qnp/artifacts/MemoScope_x86_Debug.zip) of MemoScope and tell me happens ?**

**Or could you send me the dump file you're loading ?**

**Comment by artisticcheese** [comment]
Here is what I got when I tried to load with debug version
![image](https://cloud.githubusercontent.com/assets/13176884/24579074/bb30b09c-16b3-11e7-888b-960359f8adac.png)

**Comment by fremag** [comment]
It looks like this exception is thrown by [DbgHelp.dll](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679309(v=vs.85).aspx), used by Memoscope to load the dump file. 
It may mean the dump file is corrupted (it may happen if the garbage collector was moving things during the dump)
You can try to load the file with WinDbg to confirm. 
If WinDbg can't load your file, Memoscope won't be able to load it too.
I'm sorry I have no better answer at the moment.

Or you to dump again your application and try to load the new file ?

**Comment by artisticcheese** [comment]
Yes. It was corrupt file.
