### ISSUE TITLE
Question: Viewing a breakdown of the types that allocated the instances of a certain type

### ISSUE THREAD

**Issue by kimsagro1** [fremag/MemoScope.Net#200]
From the Heap statistics screen, I can see that a number of strings have been allocated

![image](https://cloud.githubusercontent.com/assets/6754658/25070675/557aefe2-22e8-11e7-92ac-b69e9381102b.png)

However, is there anyway to get a breakdown of the various types that allocated these strings and how many they allocated.

For example if I open the dump file in visual studio 2017, I can see this information

![image](https://cloud.githubusercontent.com/assets/6754658/25070696/2a9cde1a-22e9-11e7-99b5-0f392c2ec070.png)

Which tells me that the majority of string allocations are from a static `List<string>` named `Threes` on the `Yahoo.Yui.Compressor.JavaScriptCompressor` type

Thanks for this amazing project

**Comment by fremag** [comment]
There is a module named [Referers](https://github.com/fremag/MemoScope.Net/wiki/Referers) that may be what you're looking for:
![image](https://raw.githubusercontent.com/wiki/fremag/MemoScope.Net/img/MemoScope_Referers_Results.png)

**Comment by kimsagro1** [comment]
This doesn't really help either 
![image](https://cloud.githubusercontent.com/assets/6754658/25107856/4936a34c-2415-11e7-9aa5-f5557fc11983.png)

The program in its entirety is below if you want to have a look

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Yahoo.Yui.Compressor;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            // import nuget package YUICompressor.NET
            new JavaScriptCompressor().Compress("var a;");
            Console.ReadLine();
        }
    }
}
```

**Comment by fremag** [comment]
It looks like VS 2017 analyzes every path to root from string instances.
I wrote Memoscope with VS 2015 and installed 2017 only a few weeks ago.
Is this feature available with community edition or do you have a professional one ?

So, your question was:
"is there anyway to get a breakdown of the various types that allocated these strings and how many they allocated." and I'm sorry the answer is "No".

Maybe in a MemoScope version 1.x, who knows...

**Comment by fremag** [comment]
Correct me if I'm wrong: you used the memory profiler from VS 2017, you did not dumped your process then opened it with Visual Studio ?

That's a major difference: MemoScope is not a memory profiler.
It doesn't record anything at runtime (ie allocations), it just takes a snapshot of all the memory.

I made a screenshot of VS 2017 running your code with memory profiler activated and a dump file opened in MemoScope.
![image](https://cloud.githubusercontent.com/assets/14943271/25201724/0b0734e4-2553-11e7-89e5-46044c6ca645.png)

* VS 2017 can display the name of the static variable referencing the List<string> objects
* MemoScope just displays the index of an static object[] array

That's interesting, I wonder why it doesn't find the references from static variables.

**Comment by kimsagro1** [comment]
So the process was

1) I took a memory dump using task manager
2) I opened that dump file using vs2017 enterprise (double clicked on the .dmp file)
3) In the actions, clicked debug managed memory

![image](https://cloud.githubusercontent.com/assets/6754658/25204515/2243410e-25a1-11e7-9df5-e1ad18bc403b.png)

4) Then clicked the little icon that appears when you hover over `List<String>`

![image](https://cloud.githubusercontent.com/assets/6754658/25204540/498ef046-25a1-11e7-8100-fb65b1062d75.png)

5) Which shows this

![image](https://cloud.githubusercontent.com/assets/6754658/25204566/6b67e7a4-25a1-11e7-9829-15af8e39cb06.png)

**Comment by fremag** [comment]
Thanks a lot for the details.
It looks like the memory dump features are only available in the (expensive) Enterprise edition of Visual Studio. 
And MemoScope is free and open source :)

If you know any other missing feature, please tell me, I'll see if I can add them (or merge any pull request from a fork)

![image](https://cloud.githubusercontent.com/assets/14943271/25251029/2d2cef08-2618-11e7-830f-fd322314e666.png)
