### ISSUE TITLE
Cannot dump memory on a vmware virtual machine?

### ISSUE THREAD

**Issue by Guymestef** [fremag/MemoScope.Net#204]
Hello,

As hinted with the issue title, I'm trying to dump the memory of a process running on a virtual machine. But I can't because I get not enough space on disk.
The error is most probably due to the virtual memory size. As we can see on the process details, the virtual memory is very high:

![image](https://user-images.githubusercontent.com/685890/36639418-5c5b02d6-1a0c-11e8-9684-02f5dc8dd392.png)

I don't know if this amount is right or not...

For information, if I dump the process with the task manager, the dump is around 400Mo.

Env:
OS: Windows Server 2012 R2 Standard x64 (VM on a vmware server)
Process: dotnet.exe

**Comment by fremag** [comment]
Hello,

I tried to dump a process running on a VM (Windows Server 2016 / HyperV) and had no issue: I could dump it and load the data in Memoscope. 
I'm sorry but I have no idea why it fails in your environment.
I agree that 2 Tb of virtual memory is uncommon and maybe the root of the problem but I don't know why TaskManager can dump it while Memoscope fails...

**Comment by Guymestef** [comment]
Maybe the difference is that MemoScope is checking if there is enough space on disk to save the dump and use the total memory size (so here > 2Tb) and Task manager only the memory currently used by the process (here ~330Mb)
Anyway, since I was able to dump via Task manger and open the dump with MemoScope, it's not a big problem.
Thanks for the quick reply

**Comment by fremag** [comment]
You're right. I forgot I write a [check about available disk space based on virtual memory](https://github.com/fremag/MemoScope.Net/blob/master/MemoScope/Modules/Process/ProcessModule.cs#L169L172)

```c#
                    if (proc.Process.VirtualMemorySize64 >= driveInfo.AvailableFreeSpace)
                    {
                        Log($"Can't dump: not enough space on disk ! Proce VirtualMem: {proc.Process.VirtualMemorySize64:###,###,###,###}, available disk space: {driveInfo.AvailableFreeSpace:###,###,###,###}, drive: {driveInfo.Name}", LogLevelType.Warn);
                        return;
                    }

```

Maybe I should use PrivateMemorySize64 or PagedMemorySize64 instead.
Thanks for your help and feedback.

**Comment by LorenzoFarro** [comment]
Just wanted to add that I'm seeing the same thing. Happy to provide more information if you decide to ever look further into it. Otherwise just adding to the conversation. Working on Windows Home 11, physical machine, total virtual memory ~ 40 gb.
![image](https://user-images.githubusercontent.com/10556608/173706016-dffea8c2-2a95-4894-bc9b-0af6bbd8c54d.png)
