### ISSUE TITLE
[Feature Request] also display total size in string analysis

### ISSUE THREAD

**Issue by jeremymeng** [fremag/MemoScope.Net#205]
It would be nice to include a Total Size column for this so we get a better idea of how much the duplicates cost

![image](https://user-images.githubusercontent.com/7583839/51761282-8a058b80-2081-11e9-9b88-48844a8699ed.png)

**Comment by fremag** [comment]
Good idea. Thanks. I'll do this for next release.

**Comment by fremag** [comment]
![image](https://user-images.githubusercontent.com/14943271/59566636-f6018400-9062-11e9-9e7c-982c8f0c68dd.png)
