### ISSUE TITLE
x32 image, dumped with x64 task manager loading error

### ISSUE THREAD

**Issue by joo0ne** [fremag/MemoScope.Net#206]
When try to load in memoscope x86 version, image dumped from x32 process, but with x64 task manager, i got this error:
------------------
Failed to load dump file: xxx.DMP
Exception: Wrong architecture ! Dumpfile : 64 bits, Environment.Is64BitProcess : False
------------------

WinDbg x32 open correct.

**Comment by stej** [comment]
If i'm not mistaken, bittness of the process used for dump (task manager) should be the same as the bittness of the proces.
