### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by Zero3** [fremag/MemoScope.Net#208]
The download links in both `README.md` and in the wiki are broken :(

**Comment by fremag** [comment]
Thanks for notifying this.

There are some issues with AppVeyor. I'll fix this as soon as possible (I'm away from keyboard this week)

Meanwhile, you can get the binaries in the 'releases' section of the repository.

**Comment by fremag** [comment]
Fixed, there was a credential issue between Github and AppVeyor.
