### ISSUE TITLE
Download links for binaries are not available anymore

### ISSUE THREAD

**Issue by VolkmarR** [fremag/MemoScope.Net#214]
Hi.

I tried to download the binaries for this tool, but it seems that they do net exist anymore. This is the error message shown in the browser

    <Error>
        <Code>BlobNotFound</Code>
        <Message>
            The specified blob does not exist. RequestId:c34906d2-d01e-008e-5bee-3fdaac000000 Time:2020-06-11T12:50:48.0322913Z
        </Message>
    </Error>`

**Comment by fremag** [comment]
Hi,

Thanks for notifying me, AppVeyor is keeping build artefacts only 6 months that's why the link didn't work. I've rebuilt the project so it should be good now.

You can download the latest release from Github too: https://github.com/fremag/MemoScope.Net/releases

**Comment by VolkmarR** [comment]
If you like, then I could invest some time and add a nuke build script that uses GitHub actions to build the artifacts. That would solve the appveyor problen.

**Comment by fremag** [comment]
I'm looking at GitHub actions but it looks like artifacts are kept only 90 days (https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#about-workflow-artifacts)

I'm sure you know more than me about Actions so, please, could you explain to me what you wanted to do ?

**Comment by VolkmarR** [comment]
I know very little about github actions. I used nuke.build, that creates a github action script. It seems, that github distinguishes between build artifacts and [release assets](https://help.github.com/en/github/administering-a-repository/about-releases). When you create a release (by using a release tag). So the releasing could be, that you create a new release tag in github. That triggers a github action that builds and uploads the release asset.
