### ISSUE TITLE
Can you advise how to extract .dll files from dmp

### ISSUE THREAD

**Issue by ttodua** [fremag/MemoScope.Net#215]
if we dump process with MemoScope, it saves large .dmp & .sql files.
Can you advise how we can extract .dll files from dmp to analyze in ILspy?
actually, i want to find method body of specific class.

**Comment by fremag** [comment]
Sorry but I still have no idea how to do that (cf #212)
Clrmd has released a version 2.0 but I didn't see a method to extract dll files from dump.
